name: Simple-demo
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: run a sample action
        run: echo hello world

      - name: upload artifact
      - uses: actions/upload-artifact@v4.6.0
        with:
          name: my-files
          path: ${{github.workspace}}
